name: CIDC pipeline

on:
  push:
    branches:
      - master # Changing the branch here would also work.
      - new-branch
  pull_request:
    branches:
      - new-branch
      - master
    types:
      - "opened"
      - "synchronize"

env:
  NODE_VERSION: "14.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          npm run eslint

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* .env .next

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: unzip artifact for deployment
        run: |
          unzip release.zip

      - name: "Deploy to Heroku WebApp"
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pipeline--practice" #Must be unique in Heroku
          heroku_email: "omobolaji.koyi@yahoo.com"
          buildpack: "https://github.com/HashNuke/heroku-buildpack-elixir.git"
          healthcheck: "https://pipeline--practice.herokuapp.com/health"
          checkstring: "ok"
          justlogin: true
          delay: 5
          rollbackonhealthcheckfailed: true
        env:
          HD_FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
          HD_RANDOM_DATA: "Hello"
  context:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "github context"
        env:
          GITHUB_CONTEXT: ${{toJSON(github)}}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{toJSON(github.event.commits)}}
        run: echo "$COMMITS"
      - name: commit timestamp
        env:
          COMMITS_TIMESTAMP: ${{toJSON(github.event.commits[0].timestamp)}}
        run: echo "$COMMITS_TIMESTAMP"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{toJSON(github.event.commits.*.message)}}
        run: echo "$COMMIT_MESSAGES"
  # Deploy-on-gh-pages:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: node-app

  #     - name: unzip artifact for deployment
  #       run: |
  #         unzip release.zip

  #     # - uses: actions/setup-node@v2
  #     # - run: npm run build --if-present
  #     - name: Deploy 🚀
  #       uses: JamesIves/github-pages-deploy-action@v4.2.5
  #       with:
  #         branch: gh-pages # The branch the action should deploy to.
  #         folder: dist # The folder the action should deploy.
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.github_token }}
