name: Hello World!
on:
  push:
    branches:
      - "master"
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
          echo "Hi!!"
      - name: show time
        run: date
      - name: directory container
        run: ls -l
