name: Deploy

on:
  push:
    branches:
      - master # Changing the branch here would also work.
      - new-branch
  pull_request:
    branches:
      - new-branch
      - master
    types:
      - "opened"
      - "synchronize"

jobs:
  build:
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' }} #step will run when there is a push or merge event
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: |
          npm install
          npm run test
          npm run eslint
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          WITH_V: true
          DEFAULT_BUMP: patch
      - run: echo 'job-build'

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pipeline--practice" #Must be unique in Heroku
          heroku_email: "omobolaji.koyi@yahoo.com"
          buildpack: "https://github.com/HashNuke/heroku-buildpack-elixir.git"
          healthcheck: "https://pipeline--practice.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true
        env:
          HD_FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}} # just playing around with env variables
          HD_RANDOM_DATA: "Hello"
      - run: echo 'job-deploy'
  context:
    runs-on: ubuntu-18.04
    steps:
      - name: github context
        env:
          GITHUB_CONTEXT: ${{toJSON(github)}}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{toJSON(github.event.commits)}}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{toJSON(github.event.commits.*.message)}}
        run: "$COMMIT_MESSAGES"
      - run: echo 'job-context'
