name: Deployment pipeline
on:
  push:
    branches:
      - "master"
      - "fullstack-test"
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup
        with:
          node-version: "12.x"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
